import type { Metadata } from "next";
import "@/_modules/shared/css/globals.css";
import "@/_modules/shared/css/color-theme.css"
import "@/_modules/shared/css/typology.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased theme-dark color-bg`}
      >
        <div className={'color-bg app-holder flex justify-center items-center'}>
          <div className="app-content p-3">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
